### ISSUE TITLE
Option to disable terrain in maps

### ISSUE THREAD

**Issue by bannmann** [LeagueOfAutomatedNations/Screeps-LoAN#110]
The maps on the LOAN website render awfully slow. Perhaps it would improve performance if there was an option to disable fetching/rendering of terrain data. If enabled, the option should be persisted in a cookie for subsequent visits.

Ideally, if terrain data is disabled, we would have two background colors, a darker shade for the sectors and a lighter shade for the highway rooms between sectors.

**Comment by tedivm** [comment]
The terrain map is the easiest part to load- it's just a static image. The real load is on building and rendering the alliance data itself.
