### ISSUE TITLE
Missidentified Clone Overmind

### ISSUE THREAD

**Issue by Elither** [LeagueOfAutomatedNations/Screeps-LoAN#144]
When I currently check the listing of clones on shard3 I (Elither, room E44S1) show up as an overmind clone when I know I'm definatley not. I just started yesterday and my code is probably a mess. When I first tested the signing feature I included the word overmind if that makes any difference? But I'm not an overmind and it lists me as one.

**Comment by tedivm** [comment]
You're right, it might have been your controller signature that pushed the heuristics over the edge If you're not running the overmind code it'll clear out on it's own in at most three days.

**Comment by tedivm** [comment]
If it's still labeled as overmind after that feel free to reopen.

**Comment by Elither** [comment]
Hey, This is still an issue as it still says I am an overmind still, after 4 days, Im not sure I can reopen the issue though.

**Comment by ags131** [comment]
Looks like the scan hung up a couple days ago, and hasn't scanned since. I've poked it back into working, its also showing you as unique now :)
