### ISSUE TITLE
404 page not found

### ISSUE THREAD

**Issue by Akuukis** [LeagueOfAutomatedNations/Screeps-LoAN#159]
Link in the description http://www.leagueofautomatednations.com/ is down with `404 page not found`, as well as https://www.leagueofautomatednations.com/

**Comment by pieterbrandsen** [comment]
@Akuukis  https://loan.pandascreeps.com works, I will fix this

**Comment by pieterbrandsen** [comment]
Please test @Akuukis  It works now also

**Comment by Akuukis** [comment]
HTTPS works :+1: but HTTP doesn't :-1: 

Usually you can create a redirect from HTTP to HTTPS?

**Comment by pieterbrandsen** [comment]
@Akuukis Retest please :)

**Comment by Akuukis** [comment]
Still the same, even with hard refresh (CTRL+F5).

**Comment by pieterbrandsen** [comment]
@Akuukis  We fixed it now
