### ISSUE TITLE
Change Color

### ISSUE THREAD

**Issue by cyberblast** [LeagueOfAutomatedNations/Screeps-LoAN#61]
It should be possible to change a selected alliance color. 
(I selected white and as the color seems to be used as font color (on a static white background) its not readable).

**Comment by cyberblast** [comment]
current problem solved by uncommenting the picker on the (rendered) page. 
Until the next alliance with white color gets created 😆

**Comment by tedivm** [comment]
Alliances can no longer set or update their colors, and they all get set to black automatically when any profile data for the alliance is updated.
