### ISSUE TITLE
manage alliance Error 400

### ISSUE THREAD

**Issue by cyberblast** [LeagueOfAutomatedNations/Screeps-LoAN#62]
When clicking "Save" on the alliance management page (/my/updateprofile) (e.g. to set the slack channel) it returns a code 400 and nothing is saved. 
"Submit" above (for invite or Image submission) works fine...

**Comment by cyberblast** [comment]
Save also works again when uncommenting the picker on the (rendered) page. color is a required parameter in update_all_alliances_info...

**Comment by tedivm** [comment]
Should be resolved.
