### ISSUE TITLE
Alliances in which all players have left still exist, and alliances with only one player alive are still shown

### ISSUE THREAD

**Issue by daboross** [LeagueOfAutomatedNations/Screeps-LoAN#63]
When all players have left an alliance, it is still shown on the sidebar on the map and on the main alliance page - even though there's literally no way for any new players to join the alliance.

Additionally, when only one player is left in an alliance, the alliance is still shown on the map. I would think that it might still be useful to show one-player alliances in some situations, but it may also be desirable to hide them.

**Comment by tedivm** [comment]
Half done- alliances with less than two members are no longer in the alliances.js file, and thus not on the map. They still show up on the listing through.

**Comment by daboross** [comment]
Fixed now
