### ISSUE TITLE
Saving info for CoPS alliance returns BAD REQUEST

### ISSUE THREAD

**Issue by kotarou** [LeagueOfAutomatedNations/Screeps-LoAN#71]
Add a slack channel "cops_public" to the CopS alliance returns: "Bad Request - The browser (or proxy) sent a request that this server could not understand. "

Reproduction steps: Log in, navigate to My Alliance, write "cops_public" into slack field, save.

Testing.... I don't even need to add a slack channel. Pressing save without making changes returns same issue.

Browser is Chrome Version 54.0.2840.99 m (64-bit)

**Comment by tedivm** [comment]
I replicated the issue and resolved it, so you should be good to update things.
