### ISSUE TITLE
Can not open "charter" tab on "My Alliance" page

### ISSUE THREAD

**Issue by DomNomNom** [LeagueOfAutomatedNations/Screeps-LoAN#93]
Steps to reproduce:

1. Go to the [My Alliance page](http://www.leagueofautomatednations.com/my) 

2. Click on "Charter"

Expected behaviour:

- The charter page shows.

Observed behaviour:
- Only the url changes to `http://www.leagueofautomatednations.com/my#panel2`.

**Comment by tedivm** [comment]
Fixed.
